### ISSUE TITLE
汤不热看非 1080p60fps 1440自动关闭

### ISSUE THREAD

**Issue by nzcool** [yvbbrjdr/pipesocks-iOS#2]
看youtube1080  1440都没有自动关闭的现象。看汤不热的小视频反而关闭！

**Comment by yvbbrjdr** [comment]
OK, I will look into this problem right away.

If it's still unsolvable, we'll have to wait for libnekit or I will change to tun2socks.

Thank you for your report, anyway!

**Comment by nzcool** [comment]
不用谢，pipe非常不错，支持

**Comment by nzcool** [comment]
今天用测速软件测速也会跳掉，后来，我重新启动服务端，就发现又可以了。测试汤不热也可以正常。难道还是服务端问题？

**Comment by yvbbrjdr** [comment]
Strange😂
